import type { ItemCategory, PackingLocations, CatalogCategory } from "../types";

export interface ItemMasterEntry {
  name: string;
  category: ItemCategory;
  catalogCategory: CatalogCategory;
  isIssuedByTeam: boolean;
  needsSize?: boolean;
  qtyRequired: number;
  notes?: string;
  packing: PackingLocations;
}

const p0: PackingLocations = {
  deploymentUniform: 0,
  bag24hr: 0,
  rollerBag: 0,
  webGear: 0,
  webGearBag: 0,
  coldWeatherBag: 0,
};

export const ITEMS_MASTER: ItemMasterEntry[] = [
  // ── BAGS & WEB GEAR ──────────────────────────────────────────────────
  {
    name: "Large Roller Bag (90 lbs. MAX)",
    category: "bags",
    catalogCategory: "packs-bags",
    isIssuedByTeam: true,
    qtyRequired: 1,
    packing: { ...p0 },
  },
  {
    name: "24 Hour Pack (35 lbs. MAX)",
    category: "bags",
    catalogCategory: "packs-bags",
    isIssuedByTeam: true,
    qtyRequired: 1,
    packing: { ...p0 },
  },
  {
    name: "Web Gear Bag (40 lbs. MAX)",
    category: "bags",
    catalogCategory: "packs-bags",
    isIssuedByTeam: true,
    qtyRequired: 1,
    packing: { ...p0 },
  },
  {
    name: "Web Gear & Belt Kit",
    category: "bags",
    catalogCategory: "packs-bags",
    isIssuedByTeam: true,
    qtyRequired: 1,
    packing: { ...p0, webGearBag: 1 },
  },
  {
    name: "Cold Weather Bag (40 lbs. MAX)",
    category: "bags",
    catalogCategory: "packs-bags",
    isIssuedByTeam: true,
    qtyRequired: 1,
    packing: { ...p0 },
  },

  // ── PATCHES ───────────────────────────────────────────────────────────
  {
    name: "American Flag BDU Patch",
    category: "patches",
    catalogCategory: "patches",
    isIssuedByTeam: true,
    qtyRequired: 2,
    notes: "For 3-in-1 Parka",
    packing: { ...p0, bag24hr: 1, rollerBag: 1 },
  },
  {
    name: "CA-TF2 Shoulder Patch",
    category: "patches",
    catalogCategory: "patches",
    isIssuedByTeam: true,
    qtyRequired: 2,
    packing: { ...p0, deploymentUniform: 1, rollerBag: 1 },
  },
  {
    name: "CA-TF2 Rocker",
    category: "patches",
    catalogCategory: "patches",
    isIssuedByTeam: true,
    qtyRequired: 2,
    packing: { ...p0, deploymentUniform: 1, rollerBag: 1 },
  },
  {
    name: "CA-TF2 Large Back Patch",
    category: "patches",
    catalogCategory: "patches",
    isIssuedByTeam: true,
    qtyRequired: 2,
    packing: { ...p0, deploymentUniform: 1, rollerBag: 1 },
  },
  {
    name: "FEMA Shoulder Patch",
    category: "patches",
    catalogCategory: "patches",
    isIssuedByTeam: true,
    qtyRequired: 2,
    packing: { ...p0, deploymentUniform: 1, rollerBag: 1 },
  },
  {
    name: "CAL OES Patch",
    category: "patches",
    catalogCategory: "patches",
    isIssuedByTeam: true,
    qtyRequired: 1,
    packing: { ...p0, deploymentUniform: 1 },
  },

  // ── BOOTS ─────────────────────────────────────────────────────────────
  {
    name: "Globe Rescue Boots",
    category: "boots",
    catalogCategory: "footwear",
    isIssuedByTeam: true,
    needsSize: true,
    qtyRequired: 1,
    packing: { ...p0, deploymentUniform: 1 },
  },
  {
    name: "Quad Certified Dept. Issued Boots",
    category: "boots",
    catalogCategory: "footwear",
    isIssuedByTeam: false,
    qtyRequired: 1,
    notes: "Use spare set of station boots",
    packing: { ...p0, webGearBag: 1 },
  },
  {
    name: "Wide Area Search Boots (Tan)",
    category: "boots",
    catalogCategory: "footwear",
    isIssuedByTeam: true,
    needsSize: true,
    qtyRequired: 1,
    packing: { ...p0, rollerBag: 1 },
  },
  {
    name: "Cold Weather Boots",
    category: "boots",
    catalogCategory: "footwear",
    isIssuedByTeam: true,
    needsSize: true,
    qtyRequired: 1,
    notes: "Issued at time of deployment",
    packing: { ...p0, coldWeatherBag: 1 },
  },

  // ── BDUS ──────────────────────────────────────────────────────────────
  {
    name: "BDU Top (5.11)",
    category: "bdus",
    catalogCategory: "clothing-bdus",
    isIssuedByTeam: true,
    needsSize: true,
    qtyRequired: 3,
    notes: "5.11 TDU Blouse — letter sizes (XS, S, M, L, XL, 2XL, 3XL)",
    packing: { ...p0, deploymentUniform: 1, rollerBag: 2 },
  },
  {
    name: "BDU Top (Tru-Spec)",
    category: "bdus",
    catalogCategory: "clothing-bdus",
    isIssuedByTeam: true,
    needsSize: true,
    qtyRequired: 3,
    notes: "Tru-Spec BDU Blouse — letter+length (Small Regular, Medium Long, etc.)",
    packing: { ...p0, deploymentUniform: 1, rollerBag: 2 },
  },
  {
    name: "BDU Pants (5.11)",
    category: "bdus",
    catalogCategory: "clothing-bdus",
    isIssuedByTeam: true,
    needsSize: true,
    qtyRequired: 3,
    notes: "5.11 EMS Pants — waist×inseam (e.g. 32X32)",
    packing: { ...p0, deploymentUniform: 1, rollerBag: 2 },
  },
  {
    name: "BDU Pants (Tru-Spec)",
    category: "bdus",
    catalogCategory: "clothing-bdus",
    isIssuedByTeam: true,
    needsSize: true,
    qtyRequired: 3,
    notes: "Tru-Spec BDU Pants — letter+length (Small Regular, Medium Long, etc.)",
    packing: { ...p0, deploymentUniform: 1, rollerBag: 2 },
  },
  {
    name: "BDU Shorts",
    category: "bdus",
    catalogCategory: "clothing-bdus",
    isIssuedByTeam: true,
    needsSize: true,
    qtyRequired: 1,
    packing: { ...p0, rollerBag: 1 },
  },
  {
    name: "Belt",
    category: "bdus",
    catalogCategory: "clothing-bdus",
    isIssuedByTeam: true,
    needsSize: true,
    qtyRequired: 1,
    packing: { ...p0, deploymentUniform: 1 },
  },

  // ── CLOTHING (Team Issued) ────────────────────────────────────────────
  {
    name: "CA-TF2 Short Sleeve T-shirt",
    category: "clothing",
    catalogCategory: "clothing-shirts",
    isIssuedByTeam: true,
    needsSize: true,
    qtyRequired: 5,
    packing: { ...p0, deploymentUniform: 1 },
  },
  {
    name: "CA-TF2 Long Sleeve T-shirt",
    category: "clothing",
    catalogCategory: "clothing-shirts",
    isIssuedByTeam: true,
    needsSize: true,
    qtyRequired: 5,
    packing: { ...p0, bag24hr: 1, coldWeatherBag: 4 },
  },
  {
    name: "CA-TF2 Polo Short Sleeve",
    category: "clothing",
    catalogCategory: "clothing-shirts",
    isIssuedByTeam: true,
    needsSize: true,
    qtyRequired: 1,
    packing: { ...p0, rollerBag: 1 },
  },
  {
    name: "CA-TF2 Polo Long Sleeve",
    category: "clothing",
    catalogCategory: "clothing-shirts",
    isIssuedByTeam: true,
    needsSize: true,
    qtyRequired: 1,
    packing: { ...p0, rollerBag: 1 },
  },
  {
    name: "Water Shirt",
    category: "clothing",
    catalogCategory: "clothing-shirts",
    isIssuedByTeam: true,
    needsSize: true,
    qtyRequired: 1,
    packing: { ...p0, rollerBag: 1 },
  },
  {
    name: "Boardshorts",
    category: "clothing",
    catalogCategory: "clothing-shirts",
    isIssuedByTeam: true,
    needsSize: true,
    qtyRequired: 1,
    packing: { ...p0, rollerBag: 1 },
  },
  {
    name: "3-in-1 Parka",
    category: "clothing",
    catalogCategory: "clothing-outerwear",
    isIssuedByTeam: true,
    needsSize: true,
    qtyRequired: 1,
    packing: { ...p0, bag24hr: 1 },
  },
  {
    name: "Boot Gaiters Pair",
    category: "clothing",
    catalogCategory: "clothing-outerwear",
    isIssuedByTeam: true,
    qtyRequired: 1,
    packing: { ...p0, coldWeatherBag: 1 },
  },
  {
    name: "Rain Pants",
    category: "clothing",
    catalogCategory: "clothing-outerwear",
    isIssuedByTeam: true,
    needsSize: true,
    qtyRequired: 1,
    packing: { ...p0, bag24hr: 1 },
  },
  {
    name: "Baseball Hat",
    category: "clothing",
    catalogCategory: "clothing-headwear",
    isIssuedByTeam: true,
    qtyRequired: 1,
    packing: { ...p0, deploymentUniform: 1 },
  },
  {
    name: "Boonie Hat",
    category: "clothing",
    catalogCategory: "clothing-headwear",
    isIssuedByTeam: true,
    qtyRequired: 1,
    packing: { ...p0 },
  },
  {
    name: "Beanie",
    category: "clothing",
    catalogCategory: "clothing-headwear",
    isIssuedByTeam: true,
    qtyRequired: 1,
    packing: { ...p0, bag24hr: 1 },
  },
  {
    name: "Head/Neck Gaiter",
    category: "clothing",
    catalogCategory: "clothing-headwear",
    isIssuedByTeam: true,
    qtyRequired: 1,
    packing: { ...p0, bag24hr: 1 },
  },

  // ── CLOTHING (Personal) ──────────────────────────────────────────────
  {
    name: "Socks",
    category: "clothing",
    catalogCategory: "clothing-personal",
    isIssuedByTeam: false,
    qtyRequired: 10,
    packing: { ...p0, bag24hr: 1, rollerBag: 9 },
  },
  {
    name: "Socks Cold Weather",
    category: "clothing",
    catalogCategory: "clothing-personal",
    isIssuedByTeam: false,
    qtyRequired: 6,
    notes: "wool socks recommended",
    packing: { ...p0, coldWeatherBag: 6 },
  },
  {
    name: "Underwear",
    category: "clothing",
    catalogCategory: "clothing-personal",
    isIssuedByTeam: false,
    qtyRequired: 10,
    notes: "Quick-dry performance recommended",
    packing: { ...p0, bag24hr: 1, rollerBag: 9 },
  },
  {
    name: "Shoes Casual (Black Tennis Shoes)",
    category: "clothing",
    catalogCategory: "clothing-personal",
    isIssuedByTeam: false,
    qtyRequired: 1,
    packing: { ...p0, rollerBag: 1 },
  },
  {
    name: "Shoes Shower",
    category: "clothing",
    catalogCategory: "clothing-personal",
    isIssuedByTeam: false,
    qtyRequired: 1,
    packing: { ...p0, rollerBag: 1 },
  },
  {
    name: "Lightweight Khaki Civilian Pants (NON-Fire)",
    category: "clothing",
    catalogCategory: "clothing-personal",
    isIssuedByTeam: false,
    qtyRequired: 1,
    packing: { ...p0, rollerBag: 1 },
  },
  {
    name: "Business Casual Civilian Shirt (NON-Fire)",
    category: "clothing",
    catalogCategory: "clothing-personal",
    isIssuedByTeam: false,
    qtyRequired: 1,
    packing: { ...p0, rollerBag: 1 },
  },
  {
    name: "Sweatshirt/Jacket Heavyweight Navy",
    category: "clothing",
    catalogCategory: "clothing-personal",
    isIssuedByTeam: false,
    qtyRequired: 1,
    packing: { ...p0, coldWeatherBag: 1 },
  },
  {
    name: "Gloves Lightweight Fleece",
    category: "clothing",
    catalogCategory: "clothing-personal",
    isIssuedByTeam: false,
    qtyRequired: 1,
    packing: { ...p0, coldWeatherBag: 1 },
  },
  {
    name: "Thermal Top Light Wt.",
    category: "clothing",
    catalogCategory: "clothing-outerwear",
    isIssuedByTeam: true,
    needsSize: true,
    qtyRequired: 2,
    packing: { ...p0, coldWeatherBag: 2 },
  },
  {
    name: "Thermal Bottom Light Wt.",
    category: "clothing",
    catalogCategory: "clothing-outerwear",
    isIssuedByTeam: true,
    needsSize: true,
    qtyRequired: 2,
    packing: { ...p0, coldWeatherBag: 2 },
  },

  // ── PPE & EQUIPMENT ──────────────────────────────────────────────────
  {
    name: "Gloves, Work (Leather)",
    category: "ppe",
    catalogCategory: "ppe-equipment",
    isIssuedByTeam: true,
    needsSize: true,
    qtyRequired: 1,
    packing: { ...p0, deploymentUniform: 1 },
  },
  {
    name: "Gloves, Cold Weather Work",
    category: "ppe",
    catalogCategory: "ppe-equipment",
    isIssuedByTeam: true,
    needsSize: true,
    qtyRequired: 1,
    packing: { ...p0, coldWeatherBag: 1 },
  },
  {
    name: "Gloves, Cold Weather (Insulated)",
    category: "ppe",
    catalogCategory: "ppe-equipment",
    isIssuedByTeam: true,
    needsSize: true,
    qtyRequired: 1,
    packing: { ...p0, coldWeatherBag: 1 },
  },
  {
    name: "WMD Kit (Scott Mask, Adapters, Bag)",
    category: "ppe",
    catalogCategory: "ppe-equipment",
    isIssuedByTeam: true,
    qtyRequired: 1,
    notes: "May be worn depending on nature of incident",
    packing: { ...p0, webGear: 1 },
  },
  {
    name: "Respirator Face Piece",
    category: "ppe",
    catalogCategory: "ppe-equipment",
    isIssuedByTeam: true,
    qtyRequired: 1,
    packing: { ...p0, webGear: 1 },
  },
  {
    name: "Respirator Cartridge Set",
    category: "ppe",
    catalogCategory: "ppe-equipment",
    isIssuedByTeam: true,
    qtyRequired: 2,
    packing: { ...p0, bag24hr: 1, webGear: 1 },
  },
  {
    name: "Flashlight",
    category: "ppe",
    catalogCategory: "ppe-equipment",
    isIssuedByTeam: true,
    qtyRequired: 1,
    packing: { ...p0 },
  },
  {
    name: "Multi-Tool",
    category: "ppe",
    catalogCategory: "ppe-equipment",
    isIssuedByTeam: true,
    qtyRequired: 1,
    notes: "Move to roller bag if commercial flight",
    packing: { ...p0, deploymentUniform: 1 },
  },
  {
    name: "Ear Plugs",
    category: "ppe",
    catalogCategory: "ppe-equipment",
    isIssuedByTeam: true,
    qtyRequired: 5,
    packing: { ...p0, bag24hr: 3, webGear: 2 },
  },
  {
    name: "Safety Glasses",
    category: "ppe",
    catalogCategory: "ppe-equipment",
    isIssuedByTeam: true,
    qtyRequired: 1,
    packing: { ...p0, webGear: 1 },
  },
  {
    name: "Structural Specialist Guide",
    category: "ppe",
    catalogCategory: "ppe-equipment",
    isIssuedByTeam: true,
    qtyRequired: 1,
    packing: { ...p0 },
  },
  {
    name: "Tech Rescue Guide",
    category: "ppe",
    catalogCategory: "ppe-equipment",
    isIssuedByTeam: true,
    qtyRequired: 1,
    packing: { ...p0, webGear: 1 },
  },
  {
    name: "USA-02 F.O.G.",
    category: "ppe",
    catalogCategory: "ppe-equipment",
    isIssuedByTeam: true,
    qtyRequired: 1,
    packing: { ...p0, webGear: 1 },
  },
  {
    name: "Shoring Guide",
    category: "ppe",
    catalogCategory: "ppe-equipment",
    isIssuedByTeam: true,
    qtyRequired: 1,
    notes: "Issued during structure collapse training",
    packing: { ...p0, webGear: 1 },
  },
  {
    name: "IFAK",
    category: "ppe",
    catalogCategory: "ppe-equipment",
    isIssuedByTeam: true,
    qtyRequired: 1,
    packing: { ...p0, webGear: 1 },
  },
  {
    name: "Brief Relief Urinal Bag",
    category: "ppe",
    catalogCategory: "ppe-equipment",
    isIssuedByTeam: true,
    qtyRequired: 1,
    packing: { ...p0, bag24hr: 1 },
  },
  {
    name: "Brief Relief Kit",
    category: "ppe",
    catalogCategory: "ppe-equipment",
    isIssuedByTeam: true,
    qtyRequired: 1,
    packing: { ...p0, bag24hr: 1 },
  },
  {
    name: "MRE",
    category: "ppe",
    catalogCategory: "ppe-equipment",
    isIssuedByTeam: true,
    qtyRequired: 2,
    packing: { ...p0, bag24hr: 2 },
  },
  {
    name: "Insect Repellant",
    category: "ppe",
    catalogCategory: "ppe-equipment",
    isIssuedByTeam: true,
    qtyRequired: 1,
    packing: { ...p0, bag24hr: 1 },
  },
  {
    name: "Sunscreen",
    category: "ppe",
    catalogCategory: "ppe-equipment",
    isIssuedByTeam: true,
    qtyRequired: 1,
    packing: { ...p0, bag24hr: 1 },
  },
  {
    name: "Bath in a Bag Wipes",
    category: "ppe",
    catalogCategory: "ppe-equipment",
    isIssuedByTeam: true,
    qtyRequired: 4,
    packing: { ...p0, bag24hr: 1, rollerBag: 3 },
  },
  {
    name: "Chemlight",
    category: "ppe",
    catalogCategory: "ppe-equipment",
    isIssuedByTeam: true,
    qtyRequired: 4,
    packing: { ...p0, bag24hr: 1, rollerBag: 3 },
  },

  // ── HELMET & ACCESSORIES ─────────────────────────────────────────────
  {
    name: "Team Wendy Helmet",
    category: "helmet",
    catalogCategory: "head-protection",
    isIssuedByTeam: true,
    needsSize: true,
    qtyRequired: 1,
    notes: "Color: ___",
    packing: { ...p0, bag24hr: 1 },
  },
  {
    name: "Goggles",
    category: "helmet",
    catalogCategory: "head-protection",
    isIssuedByTeam: true,
    qtyRequired: 1,
    packing: { ...p0, bag24hr: 1 },
  },
  {
    name: "Headlamp",
    category: "helmet",
    catalogCategory: "head-protection",
    isIssuedByTeam: true,
    qtyRequired: 1,
    packing: { ...p0, bag24hr: 1 },
  },
  {
    name: "Magpul Rails",
    category: "helmet",
    catalogCategory: "head-protection",
    isIssuedByTeam: true,
    qtyRequired: 1,
    packing: { ...p0, bag24hr: 1 },
  },
  {
    name: "Vent Covers",
    category: "helmet",
    catalogCategory: "head-protection",
    isIssuedByTeam: true,
    qtyRequired: 1,
    packing: { ...p0, bag24hr: 1 },
  },
  {
    name: "TW Helmet Decal - LA COUNTY FIRE",
    category: "helmet",
    catalogCategory: "head-protection",
    isIssuedByTeam: true,
    qtyRequired: 2,
    packing: { ...p0, bag24hr: 2 },
  },

  // ── SLEEPING BAG & ACCESSORIES ───────────────────────────────────────
  {
    name: "Emergency Bivy Sack",
    category: "sleeping",
    catalogCategory: "sleep-system",
    isIssuedByTeam: true,
    qtyRequired: 1,
    packing: { ...p0, bag24hr: 1 },
  },
  {
    name: "Sleeping Pad",
    category: "sleeping",
    catalogCategory: "sleep-system",
    isIssuedByTeam: true,
    qtyRequired: 1,
    packing: { ...p0, rollerBag: 1 },
  },
  {
    name: "Sleeping Bag",
    category: "sleeping",
    catalogCategory: "sleep-system",
    isIssuedByTeam: true,
    qtyRequired: 1,
    packing: { ...p0, rollerBag: 1 },
  },
  {
    name: "Sleeping Bag Girdle",
    category: "sleeping",
    catalogCategory: "sleep-system",
    isIssuedByTeam: true,
    qtyRequired: 1,
    packing: { ...p0, rollerBag: 1 },
  },
  {
    name: "Pillow",
    category: "sleeping",
    catalogCategory: "sleep-system",
    isIssuedByTeam: true,
    qtyRequired: 1,
    packing: { ...p0, bag24hr: 1 },
  },

  // ── PERSONAL ITEMS ───────────────────────────────────────────────────
  {
    name: "Small Waterproof Case (Pelican) for records & cash",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 1,
    packing: { ...p0, deploymentUniform: 1 },
  },
  {
    name: "Cash $300 (small bills NOT $20s)",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 1,
    packing: { ...p0, deploymentUniform: 1 },
  },
  {
    name: "Immunization Record Original",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 1,
    packing: { ...p0, deploymentUniform: 1 },
  },
  {
    name: "Immunization Record Copy",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 1,
    packing: { ...p0, rollerBag: 1 },
  },
  {
    name: "Passport Original",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 1,
    packing: { ...p0, deploymentUniform: 1 },
  },
  {
    name: "Passport Copy",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 4,
    packing: { ...p0, deploymentUniform: 1, bag24hr: 1, rollerBag: 1, coldWeatherBag: 1 },
  },
  {
    name: "Passport Photos (actual photos not copies)",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 4,
    packing: { ...p0, bag24hr: 2, rollerBag: 2 },
  },
  {
    name: "Nametape Gold on Navy Blue (max 5\")",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 4,
    packing: { ...p0, deploymentUniform: 1, rollerBag: 3 },
  },
  {
    name: "Nametape White on Black (max 5\")",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 4,
    notes: "1 on Parka, 1 on Web Gear",
    packing: { ...p0, bag24hr: 1, rollerBag: 2, webGear: 1 },
  },
  {
    name: "Small Overnight Toiletry Kit incl. Shaving Kit",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 1,
    packing: { ...p0, bag24hr: 1 },
  },
  {
    name: "Toiletry Kit Non-Aerosol",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 1,
    packing: { ...p0, rollerBag: 1 },
  },
  {
    name: "List of Medications (medic notified)",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 1,
    packing: { ...p0, bag24hr: 1 },
  },
  {
    name: "Soap Bar with Camping Case",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 1,
    packing: { ...p0, rollerBag: 1 },
  },
  {
    name: "Towel Small Backpack Type",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 1,
    packing: { ...p0, bag24hr: 1 },
  },
  {
    name: "Towel Bath Quick-Dry",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 1,
    packing: { ...p0, rollerBag: 1 },
  },
  {
    name: "Travel Sewing Kit",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 1,
    packing: { ...p0, rollerBag: 1 },
  },
  {
    name: "Fire Hood (Dept. Issued)",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 1,
    packing: { ...p0, rollerBag: 1 },
  },
  {
    name: "Compass",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 1,
    packing: { ...p0, bag24hr: 1 },
  },
  {
    name: "Parachute Cord approx. 60ft",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 1,
    packing: { ...p0, bag24hr: 1 },
  },
  {
    name: "Matches & Case Waterproof",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 1,
    packing: { ...p0, bag24hr: 1 },
  },
  {
    name: "Signal Mirror",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 1,
    packing: { ...p0, bag24hr: 1 },
  },
  {
    name: "Flashlight Batteries Spare Set",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 2,
    packing: { ...p0, webGear: 2 },
  },
  {
    name: "Headlamp Batteries Spare Set",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 2,
    packing: { ...p0, bag24hr: 2 },
  },
  {
    name: "Food Snack Bars",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 2,
    packing: { ...p0, bag24hr: 2 },
  },
  {
    name: "Note Pad",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 1,
    packing: { ...p0, bag24hr: 1 },
  },
  {
    name: "Pens & Pencils",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 2,
    packing: { ...p0, bag24hr: 2 },
  },
  {
    name: "Knee Pads Pair",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 1,
    packing: { ...p0, webGearBag: 1 },
  },
  {
    name: "Elbow Pads Pair",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 1,
    packing: { ...p0, webGearBag: 1 },
  },
  {
    name: "Antiseptic Wipes Package",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 1,
    packing: { ...p0, bag24hr: 1 },
  },
  {
    name: "Cutlery Kit Camping Style (no disposable in BoO)",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 1,
    packing: { ...p0, rollerBag: 1 },
  },
  {
    name: "Drinking Cup Hot/Cold",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 1,
    packing: { ...p0, rollerBag: 1 },
  },
  {
    name: "Spare Boot Laces",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 2,
    packing: { ...p0, rollerBag: 2 },
  },
  {
    name: "Zip Lock Bags 1 Gallon",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 4,
    packing: { ...p0, rollerBag: 4 },
  },
  {
    name: "Trash Bags Large",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 6,
    packing: { ...p0, rollerBag: 3, coldWeatherBag: 3 },
  },
  {
    name: "Trash Bags Small",
    category: "personal",
    catalogCategory: "personal-items",
    isIssuedByTeam: false,
    qtyRequired: 6,
    packing: { ...p0, rollerBag: 3, coldWeatherBag: 3 },
  },
];
